version: '2'
services:
  rsync:
    image: metocean/rsync
    restart: always
    volumes:
      - /data:/data_src
      - /data_backup:/data_dest
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
